dubbo:
  application:
    name: das-user
  registry:
    address: nacos://124.222.131.236:3848
  protocol:
    port: 3011

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

im-segment-id:
  enabled: true