spring:
  application:
    name: im-das-user
  rabbitmq:
    host: 124.222.131.236
    port: 3672
    username: soim
    password: sopod@rabbit#
    virtual-host: soim

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://124.222.131.236:3848
    group: im-user
  protocol:
    port: 3011

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

im-segment-id:
  enabled: true
