spring:
  application:
    name: im-das-group

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    port: 3014
  consumer:
    check: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

im-segment-id:
  enabled: true
