// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/message.proto

package net.sopod.soim.logic.common.message;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sopod_soim_logic_common_message_UserSearchReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_sopod_soim_logic_common_message_UserSearchReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sopod_soim_logic_common_message_UserSearchReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_sopod_soim_logic_common_message_UserSearchReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sopod_soim_logic_common_message_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_sopod_soim_logic_common_message_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/message.proto\022#net.sopod.soim.lo" +
      "gic.common.message\" \n\rUserSearchReq\022\017\n\007k" +
      "eyword\030\001 \001(\t\"O\n\017UserSearchReply\022<\n\005users" +
      "\030\001 \003(\0132-.net.sopod.soim.logic.common.mes" +
      "sage.UserInfo\":\n\010UserInfo\022\013\n\003uid\030\001 \001(\003\022\017" +
      "\n\007account\030\002 \001(\t\022\020\n\010nickname\030\003 \001(\tB\002P\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_net_sopod_soim_logic_common_message_UserSearchReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_sopod_soim_logic_common_message_UserSearchReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_sopod_soim_logic_common_message_UserSearchReq_descriptor,
        new java.lang.String[] { "Keyword", });
    internal_static_net_sopod_soim_logic_common_message_UserSearchReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_sopod_soim_logic_common_message_UserSearchReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_sopod_soim_logic_common_message_UserSearchReply_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_net_sopod_soim_logic_common_message_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_net_sopod_soim_logic_common_message_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_sopod_soim_logic_common_message_UserInfo_descriptor,
        new java.lang.String[] { "Uid", "Account", "Nickname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
