// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/AccountSearch.proto

package net.sopod.soim.logic.api.friend.search;

public interface AccountInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.sopod.soim.logic.api.friend.search.AccountInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <code>string account = 2;</code>
   * @return The account.
   */
  java.lang.String getAccount();
  /**
   * <code>string account = 2;</code>
   * @return The bytes for account.
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>string nickname = 3;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 3;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();
}
