// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/AccountSearch.proto

package net.sopod.soim.logic.api.friend.search;

/**
 * Protobuf type {@code net.sopod.soim.logic.api.friend.search.ResAccountSearch}
 */
public final class ResAccountSearch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.sopod.soim.logic.api.friend.search.ResAccountSearch)
    ResAccountSearchOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResAccountSearch.newBuilder() to construct.
  private ResAccountSearch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResAccountSearch() {
    accounts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResAccountSearch();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResAccountSearch(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              accounts_ = new java.util.ArrayList<net.sopod.soim.logic.api.friend.search.AccountInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            accounts_.add(
                input.readMessage(net.sopod.soim.logic.api.friend.search.AccountInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        accounts_ = java.util.Collections.unmodifiableList(accounts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.sopod.soim.logic.api.friend.search.AccountSearch.internal_static_net_sopod_soim_logic_api_friend_search_ResAccountSearch_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.sopod.soim.logic.api.friend.search.AccountSearch.internal_static_net_sopod_soim_logic_api_friend_search_ResAccountSearch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.sopod.soim.logic.api.friend.search.ResAccountSearch.class, net.sopod.soim.logic.api.friend.search.ResAccountSearch.Builder.class);
  }

  public static final int ACCOUNTS_FIELD_NUMBER = 1;
  private java.util.List<net.sopod.soim.logic.api.friend.search.AccountInfo> accounts_;
  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<net.sopod.soim.logic.api.friend.search.AccountInfo> getAccountsList() {
    return accounts_;
  }
  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends net.sopod.soim.logic.api.friend.search.AccountInfoOrBuilder> 
      getAccountsOrBuilderList() {
    return accounts_;
  }
  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  @java.lang.Override
  public int getAccountsCount() {
    return accounts_.size();
  }
  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  @java.lang.Override
  public net.sopod.soim.logic.api.friend.search.AccountInfo getAccounts(int index) {
    return accounts_.get(index);
  }
  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  @java.lang.Override
  public net.sopod.soim.logic.api.friend.search.AccountInfoOrBuilder getAccountsOrBuilder(
      int index) {
    return accounts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < accounts_.size(); i++) {
      output.writeMessage(1, accounts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < accounts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, accounts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.sopod.soim.logic.api.friend.search.ResAccountSearch)) {
      return super.equals(obj);
    }
    net.sopod.soim.logic.api.friend.search.ResAccountSearch other = (net.sopod.soim.logic.api.friend.search.ResAccountSearch) obj;

    if (!getAccountsList()
        .equals(other.getAccountsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAccountsCount() > 0) {
      hash = (37 * hash) + ACCOUNTS_FIELD_NUMBER;
      hash = (53 * hash) + getAccountsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.sopod.soim.logic.api.friend.search.ResAccountSearch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.sopod.soim.logic.api.friend.search.ResAccountSearch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.sopod.soim.logic.api.friend.search.ResAccountSearch)
      net.sopod.soim.logic.api.friend.search.ResAccountSearchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sopod.soim.logic.api.friend.search.AccountSearch.internal_static_net_sopod_soim_logic_api_friend_search_ResAccountSearch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sopod.soim.logic.api.friend.search.AccountSearch.internal_static_net_sopod_soim_logic_api_friend_search_ResAccountSearch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sopod.soim.logic.api.friend.search.ResAccountSearch.class, net.sopod.soim.logic.api.friend.search.ResAccountSearch.Builder.class);
    }

    // Construct using net.sopod.soim.logic.api.friend.search.ResAccountSearch.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAccountsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (accountsBuilder_ == null) {
        accounts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        accountsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.sopod.soim.logic.api.friend.search.AccountSearch.internal_static_net_sopod_soim_logic_api_friend_search_ResAccountSearch_descriptor;
    }

    @java.lang.Override
    public net.sopod.soim.logic.api.friend.search.ResAccountSearch getDefaultInstanceForType() {
      return net.sopod.soim.logic.api.friend.search.ResAccountSearch.getDefaultInstance();
    }

    @java.lang.Override
    public net.sopod.soim.logic.api.friend.search.ResAccountSearch build() {
      net.sopod.soim.logic.api.friend.search.ResAccountSearch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.sopod.soim.logic.api.friend.search.ResAccountSearch buildPartial() {
      net.sopod.soim.logic.api.friend.search.ResAccountSearch result = new net.sopod.soim.logic.api.friend.search.ResAccountSearch(this);
      int from_bitField0_ = bitField0_;
      if (accountsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          accounts_ = java.util.Collections.unmodifiableList(accounts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.accounts_ = accounts_;
      } else {
        result.accounts_ = accountsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.sopod.soim.logic.api.friend.search.ResAccountSearch) {
        return mergeFrom((net.sopod.soim.logic.api.friend.search.ResAccountSearch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.sopod.soim.logic.api.friend.search.ResAccountSearch other) {
      if (other == net.sopod.soim.logic.api.friend.search.ResAccountSearch.getDefaultInstance()) return this;
      if (accountsBuilder_ == null) {
        if (!other.accounts_.isEmpty()) {
          if (accounts_.isEmpty()) {
            accounts_ = other.accounts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAccountsIsMutable();
            accounts_.addAll(other.accounts_);
          }
          onChanged();
        }
      } else {
        if (!other.accounts_.isEmpty()) {
          if (accountsBuilder_.isEmpty()) {
            accountsBuilder_.dispose();
            accountsBuilder_ = null;
            accounts_ = other.accounts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            accountsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAccountsFieldBuilder() : null;
          } else {
            accountsBuilder_.addAllMessages(other.accounts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.sopod.soim.logic.api.friend.search.ResAccountSearch parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.sopod.soim.logic.api.friend.search.ResAccountSearch) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<net.sopod.soim.logic.api.friend.search.AccountInfo> accounts_ =
      java.util.Collections.emptyList();
    private void ensureAccountsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        accounts_ = new java.util.ArrayList<net.sopod.soim.logic.api.friend.search.AccountInfo>(accounts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.sopod.soim.logic.api.friend.search.AccountInfo, net.sopod.soim.logic.api.friend.search.AccountInfo.Builder, net.sopod.soim.logic.api.friend.search.AccountInfoOrBuilder> accountsBuilder_;

    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public java.util.List<net.sopod.soim.logic.api.friend.search.AccountInfo> getAccountsList() {
      if (accountsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(accounts_);
      } else {
        return accountsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public int getAccountsCount() {
      if (accountsBuilder_ == null) {
        return accounts_.size();
      } else {
        return accountsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public net.sopod.soim.logic.api.friend.search.AccountInfo getAccounts(int index) {
      if (accountsBuilder_ == null) {
        return accounts_.get(index);
      } else {
        return accountsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public Builder setAccounts(
        int index, net.sopod.soim.logic.api.friend.search.AccountInfo value) {
      if (accountsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountsIsMutable();
        accounts_.set(index, value);
        onChanged();
      } else {
        accountsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public Builder setAccounts(
        int index, net.sopod.soim.logic.api.friend.search.AccountInfo.Builder builderForValue) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.set(index, builderForValue.build());
        onChanged();
      } else {
        accountsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public Builder addAccounts(net.sopod.soim.logic.api.friend.search.AccountInfo value) {
      if (accountsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountsIsMutable();
        accounts_.add(value);
        onChanged();
      } else {
        accountsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public Builder addAccounts(
        int index, net.sopod.soim.logic.api.friend.search.AccountInfo value) {
      if (accountsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountsIsMutable();
        accounts_.add(index, value);
        onChanged();
      } else {
        accountsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public Builder addAccounts(
        net.sopod.soim.logic.api.friend.search.AccountInfo.Builder builderForValue) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.add(builderForValue.build());
        onChanged();
      } else {
        accountsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public Builder addAccounts(
        int index, net.sopod.soim.logic.api.friend.search.AccountInfo.Builder builderForValue) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.add(index, builderForValue.build());
        onChanged();
      } else {
        accountsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public Builder addAllAccounts(
        java.lang.Iterable<? extends net.sopod.soim.logic.api.friend.search.AccountInfo> values) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, accounts_);
        onChanged();
      } else {
        accountsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public Builder clearAccounts() {
      if (accountsBuilder_ == null) {
        accounts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        accountsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public Builder removeAccounts(int index) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.remove(index);
        onChanged();
      } else {
        accountsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public net.sopod.soim.logic.api.friend.search.AccountInfo.Builder getAccountsBuilder(
        int index) {
      return getAccountsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public net.sopod.soim.logic.api.friend.search.AccountInfoOrBuilder getAccountsOrBuilder(
        int index) {
      if (accountsBuilder_ == null) {
        return accounts_.get(index);  } else {
        return accountsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public java.util.List<? extends net.sopod.soim.logic.api.friend.search.AccountInfoOrBuilder> 
         getAccountsOrBuilderList() {
      if (accountsBuilder_ != null) {
        return accountsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(accounts_);
      }
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public net.sopod.soim.logic.api.friend.search.AccountInfo.Builder addAccountsBuilder() {
      return getAccountsFieldBuilder().addBuilder(
          net.sopod.soim.logic.api.friend.search.AccountInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public net.sopod.soim.logic.api.friend.search.AccountInfo.Builder addAccountsBuilder(
        int index) {
      return getAccountsFieldBuilder().addBuilder(
          index, net.sopod.soim.logic.api.friend.search.AccountInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
     */
    public java.util.List<net.sopod.soim.logic.api.friend.search.AccountInfo.Builder> 
         getAccountsBuilderList() {
      return getAccountsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.sopod.soim.logic.api.friend.search.AccountInfo, net.sopod.soim.logic.api.friend.search.AccountInfo.Builder, net.sopod.soim.logic.api.friend.search.AccountInfoOrBuilder> 
        getAccountsFieldBuilder() {
      if (accountsBuilder_ == null) {
        accountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.sopod.soim.logic.api.friend.search.AccountInfo, net.sopod.soim.logic.api.friend.search.AccountInfo.Builder, net.sopod.soim.logic.api.friend.search.AccountInfoOrBuilder>(
                accounts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        accounts_ = null;
      }
      return accountsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.sopod.soim.logic.api.friend.search.ResAccountSearch)
  }

  // @@protoc_insertion_point(class_scope:net.sopod.soim.logic.api.friend.search.ResAccountSearch)
  private static final net.sopod.soim.logic.api.friend.search.ResAccountSearch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.sopod.soim.logic.api.friend.search.ResAccountSearch();
  }

  public static net.sopod.soim.logic.api.friend.search.ResAccountSearch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResAccountSearch>
      PARSER = new com.google.protobuf.AbstractParser<ResAccountSearch>() {
    @java.lang.Override
    public ResAccountSearch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResAccountSearch(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResAccountSearch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResAccountSearch> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.sopod.soim.logic.api.friend.search.ResAccountSearch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

