// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/AccountSearch.proto

package net.sopod.soim.logic.api.friend.search;

public interface ResAccountSearchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.sopod.soim.logic.api.friend.search.ResAccountSearch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  java.util.List<net.sopod.soim.logic.api.friend.search.AccountInfo> 
      getAccountsList();
  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  net.sopod.soim.logic.api.friend.search.AccountInfo getAccounts(int index);
  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  int getAccountsCount();
  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  java.util.List<? extends net.sopod.soim.logic.api.friend.search.AccountInfoOrBuilder> 
      getAccountsOrBuilderList();
  /**
   * <code>repeated .net.sopod.soim.logic.api.friend.search.AccountInfo accounts = 1;</code>
   */
  net.sopod.soim.logic.api.friend.search.AccountInfoOrBuilder getAccountsOrBuilder(
      int index);
}
