// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/UserSearch.proto

package net.sopod.soim.logic.api.friend.search;

public interface UserSearchReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.sopod.soim.logic.api.friend.search.UserSearchReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string keyword = 1;</code>
   * @return The keyword.
   */
  java.lang.String getKeyword();
  /**
   * <code>string keyword = 1;</code>
   * @return The bytes for keyword.
   */
  com.google.protobuf.ByteString
      getKeywordBytes();
}
