spring:
  application:
    name: im-das-message

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    port: 3011
  consumer:
    check: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

im-segment-id:
  enabled: true
