// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/chat/Chat.proto

package net.sopod.soim.data.msg.chat;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.TextChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送者uid
     * </pre>
     *
     * <code>int64 sender = 1;</code>
     * @return The sender.
     */
    long getSender();

    /**
     * <pre>
     * 接收者uid
     * </pre>
     *
     * <code>int64 receiver = 2;</code>
     * @return The receiver.
     */
    long getReceiver();

    /**
     * <pre>
     * 文本消息内容
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 文本消息内容
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int64 time = 4;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <pre>
     * 接收者账号
     * </pre>
     *
     * <code>string receiverAccount = 5;</code>
     * @return The receiverAccount.
     */
    java.lang.String getReceiverAccount();
    /**
     * <pre>
     * 接收者账号
     * </pre>
     *
     * <code>string receiverAccount = 5;</code>
     * @return The bytes for receiverAccount.
     */
    com.google.protobuf.ByteString
        getReceiverAccountBytes();
  }
  /**
   * <pre>
   * 文本聊天消息
   * </pre>
   *
   * Protobuf type {@code proto.TextChat}
   */
  public static final class TextChat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.TextChat)
      TextChatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextChat.newBuilder() to construct.
    private TextChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextChat() {
      message_ = "";
      receiverAccount_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TextChat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TextChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sender_ = input.readInt64();
              break;
            }
            case 16: {

              receiver_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 32: {

              time_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverAccount_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sopod.soim.data.msg.chat.Chat.internal_static_proto_TextChat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sopod.soim.data.msg.chat.Chat.internal_static_proto_TextChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sopod.soim.data.msg.chat.Chat.TextChat.class, net.sopod.soim.data.msg.chat.Chat.TextChat.Builder.class);
    }

    public static final int SENDER_FIELD_NUMBER = 1;
    private long sender_;
    /**
     * <pre>
     * 发送者uid
     * </pre>
     *
     * <code>int64 sender = 1;</code>
     * @return The sender.
     */
    @java.lang.Override
    public long getSender() {
      return sender_;
    }

    public static final int RECEIVER_FIELD_NUMBER = 2;
    private long receiver_;
    /**
     * <pre>
     * 接收者uid
     * </pre>
     *
     * <code>int64 receiver = 2;</code>
     * @return The receiver.
     */
    @java.lang.Override
    public long getReceiver() {
      return receiver_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * 文本消息内容
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文本消息内容
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int64 time = 4;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }

    public static final int RECEIVERACCOUNT_FIELD_NUMBER = 5;
    private volatile java.lang.Object receiverAccount_;
    /**
     * <pre>
     * 接收者账号
     * </pre>
     *
     * <code>string receiverAccount = 5;</code>
     * @return The receiverAccount.
     */
    @java.lang.Override
    public java.lang.String getReceiverAccount() {
      java.lang.Object ref = receiverAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverAccount_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 接收者账号
     * </pre>
     *
     * <code>string receiverAccount = 5;</code>
     * @return The bytes for receiverAccount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiverAccountBytes() {
      java.lang.Object ref = receiverAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sender_ != 0L) {
        output.writeInt64(1, sender_);
      }
      if (receiver_ != 0L) {
        output.writeInt64(2, receiver_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      if (time_ != 0L) {
        output.writeInt64(4, time_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiverAccount_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, receiverAccount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sender_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sender_);
      }
      if (receiver_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, receiver_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, time_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiverAccount_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, receiverAccount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.sopod.soim.data.msg.chat.Chat.TextChat)) {
        return super.equals(obj);
      }
      net.sopod.soim.data.msg.chat.Chat.TextChat other = (net.sopod.soim.data.msg.chat.Chat.TextChat) obj;

      if (getSender()
          != other.getSender()) return false;
      if (getReceiver()
          != other.getReceiver()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (getTime()
          != other.getTime()) return false;
      if (!getReceiverAccount()
          .equals(other.getReceiverAccount())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSender());
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiver());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + RECEIVERACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverAccount().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.chat.Chat.TextChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.sopod.soim.data.msg.chat.Chat.TextChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 文本聊天消息
     * </pre>
     *
     * Protobuf type {@code proto.TextChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.TextChat)
        net.sopod.soim.data.msg.chat.Chat.TextChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sopod.soim.data.msg.chat.Chat.internal_static_proto_TextChat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sopod.soim.data.msg.chat.Chat.internal_static_proto_TextChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sopod.soim.data.msg.chat.Chat.TextChat.class, net.sopod.soim.data.msg.chat.Chat.TextChat.Builder.class);
      }

      // Construct using net.sopod.soim.data.msg.chat.Chat.TextChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sender_ = 0L;

        receiver_ = 0L;

        message_ = "";

        time_ = 0L;

        receiverAccount_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sopod.soim.data.msg.chat.Chat.internal_static_proto_TextChat_descriptor;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.chat.Chat.TextChat getDefaultInstanceForType() {
        return net.sopod.soim.data.msg.chat.Chat.TextChat.getDefaultInstance();
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.chat.Chat.TextChat build() {
        net.sopod.soim.data.msg.chat.Chat.TextChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.chat.Chat.TextChat buildPartial() {
        net.sopod.soim.data.msg.chat.Chat.TextChat result = new net.sopod.soim.data.msg.chat.Chat.TextChat(this);
        result.sender_ = sender_;
        result.receiver_ = receiver_;
        result.message_ = message_;
        result.time_ = time_;
        result.receiverAccount_ = receiverAccount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sopod.soim.data.msg.chat.Chat.TextChat) {
          return mergeFrom((net.sopod.soim.data.msg.chat.Chat.TextChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sopod.soim.data.msg.chat.Chat.TextChat other) {
        if (other == net.sopod.soim.data.msg.chat.Chat.TextChat.getDefaultInstance()) return this;
        if (other.getSender() != 0L) {
          setSender(other.getSender());
        }
        if (other.getReceiver() != 0L) {
          setReceiver(other.getReceiver());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getReceiverAccount().isEmpty()) {
          receiverAccount_ = other.receiverAccount_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sopod.soim.data.msg.chat.Chat.TextChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sopod.soim.data.msg.chat.Chat.TextChat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sender_ ;
      /**
       * <pre>
       * 发送者uid
       * </pre>
       *
       * <code>int64 sender = 1;</code>
       * @return The sender.
       */
      @java.lang.Override
      public long getSender() {
        return sender_;
      }
      /**
       * <pre>
       * 发送者uid
       * </pre>
       *
       * <code>int64 sender = 1;</code>
       * @param value The sender to set.
       * @return This builder for chaining.
       */
      public Builder setSender(long value) {
        
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者uid
       * </pre>
       *
       * <code>int64 sender = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSender() {
        
        sender_ = 0L;
        onChanged();
        return this;
      }

      private long receiver_ ;
      /**
       * <pre>
       * 接收者uid
       * </pre>
       *
       * <code>int64 receiver = 2;</code>
       * @return The receiver.
       */
      @java.lang.Override
      public long getReceiver() {
        return receiver_;
      }
      /**
       * <pre>
       * 接收者uid
       * </pre>
       *
       * <code>int64 receiver = 2;</code>
       * @param value The receiver to set.
       * @return This builder for chaining.
       */
      public Builder setReceiver(long value) {
        
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者uid
       * </pre>
       *
       * <code>int64 receiver = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiver() {
        
        receiver_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 文本消息内容
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 文本消息内容
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文本消息内容
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文本消息内容
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文本消息内容
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>int64 time = 4;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>int64 time = 4;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>int64 time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object receiverAccount_ = "";
      /**
       * <pre>
       * 接收者账号
       * </pre>
       *
       * <code>string receiverAccount = 5;</code>
       * @return The receiverAccount.
       */
      public java.lang.String getReceiverAccount() {
        java.lang.Object ref = receiverAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverAccount_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 接收者账号
       * </pre>
       *
       * <code>string receiverAccount = 5;</code>
       * @return The bytes for receiverAccount.
       */
      public com.google.protobuf.ByteString
          getReceiverAccountBytes() {
        java.lang.Object ref = receiverAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 接收者账号
       * </pre>
       *
       * <code>string receiverAccount = 5;</code>
       * @param value The receiverAccount to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverAccount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者账号
       * </pre>
       *
       * <code>string receiverAccount = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiverAccount() {
        
        receiverAccount_ = getDefaultInstance().getReceiverAccount();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者账号
       * </pre>
       *
       * <code>string receiverAccount = 5;</code>
       * @param value The bytes for receiverAccount to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverAccount_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.TextChat)
    }

    // @@protoc_insertion_point(class_scope:proto.TextChat)
    private static final net.sopod.soim.data.msg.chat.Chat.TextChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.sopod.soim.data.msg.chat.Chat.TextChat();
    }

    public static net.sopod.soim.data.msg.chat.Chat.TextChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextChat>
        PARSER = new com.google.protobuf.AbstractParser<TextChat>() {
      @java.lang.Override
      public TextChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextChat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextChat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextChat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.sopod.soim.data.msg.chat.Chat.TextChat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TextChat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TextChat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025proto/chat/Chat.proto\022\005proto\"d\n\010TextCh" +
      "at\022\016\n\006sender\030\001 \001(\003\022\020\n\010receiver\030\002 \001(\003\022\017\n\007" +
      "message\030\003 \001(\t\022\014\n\004time\030\004 \001(\003\022\027\n\017receiverA" +
      "ccount\030\005 \001(\tB&\n\034net.sopod.soim.data.msg." +
      "chatB\004ChatP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_TextChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_TextChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TextChat_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Message", "Time", "ReceiverAccount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
