spring:
  application:
    name: im-entry
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://124.222.131.236:3848
    group: so-im
  protocol:
    name: dubbo
  # provider:
    # protocol: injvm # 服务提供只供jvm内部使用, 不暴露在外面 (不启动dubbo provider服务)
    port: 3008
  consumer:
    check: false
    filter: pre_invoke_filter

entry-server:
  nacos-addr: 124.222.131.236:3848
