spring:
  application:
    name: im-entry
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    # 启动参数 -DDUBBO_IP_TO_REGISTRY=192.168.51.7 或环境变量指定服务注册ip
    # host: 192.168.56.8 # 规则 NetUtil.isInvalidLocalHost,不能是127.x、localhost本机ip
    port: 3012
  consumer:
    check: false
    filter: pre_invoke_filter
  provider:
    listener: im_entry_export_listener
    loadbalance: im_entry_loadbalance
    timeout: 2000
    retries: 0
    register: true
