spring:
  application:
    name: im-logic-message

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    port: 3007
  consumer:
    check: false
  provider:
    retries: 0
    timeout: 2000
    filter: soimExceptionFilter,-exception