// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Hello.proto

package net.sopod.soim.data.msg.hello;

public final class HelloPB {
  private HelloPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Hello)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string str = 2;</code>
     * @return The str.
     */
    java.lang.String getStr();
    /**
     * <code>string str = 2;</code>
     * @return The bytes for str.
     */
    com.google.protobuf.ByteString
        getStrBytes();

    /**
     * <code>.proto.World world = 4;</code>
     * @return Whether the world field is set.
     */
    boolean hasWorld();
    /**
     * <code>.proto.World world = 4;</code>
     * @return The world.
     */
    net.sopod.soim.data.msg.hello.HelloPB.World getWorld();
    /**
     * <code>.proto.World world = 4;</code>
     */
    net.sopod.soim.data.msg.hello.HelloPB.WorldOrBuilder getWorldOrBuilder();
  }
  /**
   * Protobuf type {@code proto.Hello}
   */
  public static final class Hello extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Hello)
      HelloOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hello.newBuilder() to construct.
    private Hello(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hello() {
      str_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Hello();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hello(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              str_ = s;
              break;
            }
            case 34: {
              net.sopod.soim.data.msg.hello.HelloPB.World.Builder subBuilder = null;
              if (world_ != null) {
                subBuilder = world_.toBuilder();
              }
              world_ = input.readMessage(net.sopod.soim.data.msg.hello.HelloPB.World.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(world_);
                world_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_Hello_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_Hello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sopod.soim.data.msg.hello.HelloPB.Hello.class, net.sopod.soim.data.msg.hello.HelloPB.Hello.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int STR_FIELD_NUMBER = 2;
    private volatile java.lang.Object str_;
    /**
     * <code>string str = 2;</code>
     * @return The str.
     */
    @java.lang.Override
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str_ = s;
        return s;
      }
    }
    /**
     * <code>string str = 2;</code>
     * @return The bytes for str.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORLD_FIELD_NUMBER = 4;
    private net.sopod.soim.data.msg.hello.HelloPB.World world_;
    /**
     * <code>.proto.World world = 4;</code>
     * @return Whether the world field is set.
     */
    @java.lang.Override
    public boolean hasWorld() {
      return world_ != null;
    }
    /**
     * <code>.proto.World world = 4;</code>
     * @return The world.
     */
    @java.lang.Override
    public net.sopod.soim.data.msg.hello.HelloPB.World getWorld() {
      return world_ == null ? net.sopod.soim.data.msg.hello.HelloPB.World.getDefaultInstance() : world_;
    }
    /**
     * <code>.proto.World world = 4;</code>
     */
    @java.lang.Override
    public net.sopod.soim.data.msg.hello.HelloPB.WorldOrBuilder getWorldOrBuilder() {
      return getWorld();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(str_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, str_);
      }
      if (world_ != null) {
        output.writeMessage(4, getWorld());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(str_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, str_);
      }
      if (world_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getWorld());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.sopod.soim.data.msg.hello.HelloPB.Hello)) {
        return super.equals(obj);
      }
      net.sopod.soim.data.msg.hello.HelloPB.Hello other = (net.sopod.soim.data.msg.hello.HelloPB.Hello) obj;

      if (getId()
          != other.getId()) return false;
      if (!getStr()
          .equals(other.getStr())) return false;
      if (hasWorld() != other.hasWorld()) return false;
      if (hasWorld()) {
        if (!getWorld()
            .equals(other.getWorld())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + STR_FIELD_NUMBER;
      hash = (53 * hash) + getStr().hashCode();
      if (hasWorld()) {
        hash = (37 * hash) + WORLD_FIELD_NUMBER;
        hash = (53 * hash) + getWorld().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.Hello parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.sopod.soim.data.msg.hello.HelloPB.Hello prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Hello}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Hello)
        net.sopod.soim.data.msg.hello.HelloPB.HelloOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_Hello_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_Hello_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sopod.soim.data.msg.hello.HelloPB.Hello.class, net.sopod.soim.data.msg.hello.HelloPB.Hello.Builder.class);
      }

      // Construct using net.sopod.soim.data.msg.hello.HelloPB.Hello.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        str_ = "";

        if (worldBuilder_ == null) {
          world_ = null;
        } else {
          world_ = null;
          worldBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_Hello_descriptor;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.hello.HelloPB.Hello getDefaultInstanceForType() {
        return net.sopod.soim.data.msg.hello.HelloPB.Hello.getDefaultInstance();
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.hello.HelloPB.Hello build() {
        net.sopod.soim.data.msg.hello.HelloPB.Hello result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.hello.HelloPB.Hello buildPartial() {
        net.sopod.soim.data.msg.hello.HelloPB.Hello result = new net.sopod.soim.data.msg.hello.HelloPB.Hello(this);
        result.id_ = id_;
        result.str_ = str_;
        if (worldBuilder_ == null) {
          result.world_ = world_;
        } else {
          result.world_ = worldBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sopod.soim.data.msg.hello.HelloPB.Hello) {
          return mergeFrom((net.sopod.soim.data.msg.hello.HelloPB.Hello)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sopod.soim.data.msg.hello.HelloPB.Hello other) {
        if (other == net.sopod.soim.data.msg.hello.HelloPB.Hello.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getStr().isEmpty()) {
          str_ = other.str_;
          onChanged();
        }
        if (other.hasWorld()) {
          mergeWorld(other.getWorld());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sopod.soim.data.msg.hello.HelloPB.Hello parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sopod.soim.data.msg.hello.HelloPB.Hello) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object str_ = "";
      /**
       * <code>string str = 2;</code>
       * @return The str.
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string str = 2;</code>
       * @return The bytes for str.
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string str = 2;</code>
       * @param value The str to set.
       * @return This builder for chaining.
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        str_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string str = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr() {
        
        str_ = getDefaultInstance().getStr();
        onChanged();
        return this;
      }
      /**
       * <code>string str = 2;</code>
       * @param value The bytes for str to set.
       * @return This builder for chaining.
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        str_ = value;
        onChanged();
        return this;
      }

      private net.sopod.soim.data.msg.hello.HelloPB.World world_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.sopod.soim.data.msg.hello.HelloPB.World, net.sopod.soim.data.msg.hello.HelloPB.World.Builder, net.sopod.soim.data.msg.hello.HelloPB.WorldOrBuilder> worldBuilder_;
      /**
       * <code>.proto.World world = 4;</code>
       * @return Whether the world field is set.
       */
      public boolean hasWorld() {
        return worldBuilder_ != null || world_ != null;
      }
      /**
       * <code>.proto.World world = 4;</code>
       * @return The world.
       */
      public net.sopod.soim.data.msg.hello.HelloPB.World getWorld() {
        if (worldBuilder_ == null) {
          return world_ == null ? net.sopod.soim.data.msg.hello.HelloPB.World.getDefaultInstance() : world_;
        } else {
          return worldBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.World world = 4;</code>
       */
      public Builder setWorld(net.sopod.soim.data.msg.hello.HelloPB.World value) {
        if (worldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          world_ = value;
          onChanged();
        } else {
          worldBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.World world = 4;</code>
       */
      public Builder setWorld(
          net.sopod.soim.data.msg.hello.HelloPB.World.Builder builderForValue) {
        if (worldBuilder_ == null) {
          world_ = builderForValue.build();
          onChanged();
        } else {
          worldBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.World world = 4;</code>
       */
      public Builder mergeWorld(net.sopod.soim.data.msg.hello.HelloPB.World value) {
        if (worldBuilder_ == null) {
          if (world_ != null) {
            world_ =
              net.sopod.soim.data.msg.hello.HelloPB.World.newBuilder(world_).mergeFrom(value).buildPartial();
          } else {
            world_ = value;
          }
          onChanged();
        } else {
          worldBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.World world = 4;</code>
       */
      public Builder clearWorld() {
        if (worldBuilder_ == null) {
          world_ = null;
          onChanged();
        } else {
          world_ = null;
          worldBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.World world = 4;</code>
       */
      public net.sopod.soim.data.msg.hello.HelloPB.World.Builder getWorldBuilder() {
        
        onChanged();
        return getWorldFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.World world = 4;</code>
       */
      public net.sopod.soim.data.msg.hello.HelloPB.WorldOrBuilder getWorldOrBuilder() {
        if (worldBuilder_ != null) {
          return worldBuilder_.getMessageOrBuilder();
        } else {
          return world_ == null ?
              net.sopod.soim.data.msg.hello.HelloPB.World.getDefaultInstance() : world_;
        }
      }
      /**
       * <code>.proto.World world = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.sopod.soim.data.msg.hello.HelloPB.World, net.sopod.soim.data.msg.hello.HelloPB.World.Builder, net.sopod.soim.data.msg.hello.HelloPB.WorldOrBuilder> 
          getWorldFieldBuilder() {
        if (worldBuilder_ == null) {
          worldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.sopod.soim.data.msg.hello.HelloPB.World, net.sopod.soim.data.msg.hello.HelloPB.World.Builder, net.sopod.soim.data.msg.hello.HelloPB.WorldOrBuilder>(
                  getWorld(),
                  getParentForChildren(),
                  isClean());
          world_ = null;
        }
        return worldBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Hello)
    }

    // @@protoc_insertion_point(class_scope:proto.Hello)
    private static final net.sopod.soim.data.msg.hello.HelloPB.Hello DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.sopod.soim.data.msg.hello.HelloPB.Hello();
    }

    public static net.sopod.soim.data.msg.hello.HelloPB.Hello getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hello>
        PARSER = new com.google.protobuf.AbstractParser<Hello>() {
      @java.lang.Override
      public Hello parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hello(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hello> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hello> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.sopod.soim.data.msg.hello.HelloPB.Hello getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WorldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.World)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string year = 2;</code>
     * @return The year.
     */
    java.lang.String getYear();
    /**
     * <code>string year = 2;</code>
     * @return The bytes for year.
     */
    com.google.protobuf.ByteString
        getYearBytes();
  }
  /**
   * Protobuf type {@code proto.World}
   */
  public static final class World extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.World)
      WorldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use World.newBuilder() to construct.
    private World(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private World() {
      name_ = "";
      year_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new World();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private World(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              year_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_World_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_World_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sopod.soim.data.msg.hello.HelloPB.World.class, net.sopod.soim.data.msg.hello.HelloPB.World.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 2;
    private volatile java.lang.Object year_;
    /**
     * <code>string year = 2;</code>
     * @return The year.
     */
    @java.lang.Override
    public java.lang.String getYear() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        year_ = s;
        return s;
      }
    }
    /**
     * <code>string year = 2;</code>
     * @return The bytes for year.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getYearBytes() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        year_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(year_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, year_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(year_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, year_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.sopod.soim.data.msg.hello.HelloPB.World)) {
        return super.equals(obj);
      }
      net.sopod.soim.data.msg.hello.HelloPB.World other = (net.sopod.soim.data.msg.hello.HelloPB.World) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getYear()
          .equals(other.getYear())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.hello.HelloPB.World parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.sopod.soim.data.msg.hello.HelloPB.World prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.World}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.World)
        net.sopod.soim.data.msg.hello.HelloPB.WorldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_World_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_World_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sopod.soim.data.msg.hello.HelloPB.World.class, net.sopod.soim.data.msg.hello.HelloPB.World.Builder.class);
      }

      // Construct using net.sopod.soim.data.msg.hello.HelloPB.World.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        year_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sopod.soim.data.msg.hello.HelloPB.internal_static_proto_World_descriptor;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.hello.HelloPB.World getDefaultInstanceForType() {
        return net.sopod.soim.data.msg.hello.HelloPB.World.getDefaultInstance();
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.hello.HelloPB.World build() {
        net.sopod.soim.data.msg.hello.HelloPB.World result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.hello.HelloPB.World buildPartial() {
        net.sopod.soim.data.msg.hello.HelloPB.World result = new net.sopod.soim.data.msg.hello.HelloPB.World(this);
        result.name_ = name_;
        result.year_ = year_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sopod.soim.data.msg.hello.HelloPB.World) {
          return mergeFrom((net.sopod.soim.data.msg.hello.HelloPB.World)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sopod.soim.data.msg.hello.HelloPB.World other) {
        if (other == net.sopod.soim.data.msg.hello.HelloPB.World.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getYear().isEmpty()) {
          year_ = other.year_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sopod.soim.data.msg.hello.HelloPB.World parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sopod.soim.data.msg.hello.HelloPB.World) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object year_ = "";
      /**
       * <code>string year = 2;</code>
       * @return The year.
       */
      public java.lang.String getYear() {
        java.lang.Object ref = year_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          year_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string year = 2;</code>
       * @return The bytes for year.
       */
      public com.google.protobuf.ByteString
          getYearBytes() {
        java.lang.Object ref = year_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          year_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string year = 2;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string year = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = getDefaultInstance().getYear();
        onChanged();
        return this;
      }
      /**
       * <code>string year = 2;</code>
       * @param value The bytes for year to set.
       * @return This builder for chaining.
       */
      public Builder setYearBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        year_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.World)
    }

    // @@protoc_insertion_point(class_scope:proto.World)
    private static final net.sopod.soim.data.msg.hello.HelloPB.World DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.sopod.soim.data.msg.hello.HelloPB.World();
    }

    public static net.sopod.soim.data.msg.hello.HelloPB.World getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<World>
        PARSER = new com.google.protobuf.AbstractParser<World>() {
      @java.lang.Override
      public World parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new World(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<World> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<World> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.sopod.soim.data.msg.hello.HelloPB.World getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Hello_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Hello_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_World_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_World_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/Hello.proto\022\005proto\"=\n\005Hello\022\n\n\002i" +
      "d\030\001 \001(\005\022\013\n\003str\030\002 \001(\t\022\033\n\005world\030\004 \001(\0132\014.pr" +
      "oto.World\"#\n\005World\022\014\n\004name\030\001 \001(\t\022\014\n\004year" +
      "\030\002 \001(\tB*\n\035net.sopod.soim.data.msg.helloB" +
      "\007HelloPBP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Hello_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Hello_descriptor,
        new java.lang.String[] { "Id", "Str", "World", });
    internal_static_proto_World_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_World_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_World_descriptor,
        new java.lang.String[] { "Name", "Year", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
