spring:
  application:
    name: segment-id

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    port: 3001

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

im-segment-id:
  enabled: false
