// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user/UserGroup.proto

package net.sopod.soim.data.msg.user;

public final class UserGroup {
  private UserGroup() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqOnlineUserListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.sopod.soim.data.msg.user.ReqOnlineUserList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 搜索关键字
     * </pre>
     *
     * <code>string keyword = 2;</code>
     * @return The keyword.
     */
    java.lang.String getKeyword();
    /**
     * <pre>
     * 搜索关键字
     * </pre>
     *
     * <code>string keyword = 2;</code>
     * @return The bytes for keyword.
     */
    com.google.protobuf.ByteString
        getKeywordBytes();
  }
  /**
   * <pre>
   * 请求在线用户列表
   * </pre>
   *
   * Protobuf type {@code net.sopod.soim.data.msg.user.ReqOnlineUserList}
   */
  public static final class ReqOnlineUserList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.sopod.soim.data.msg.user.ReqOnlineUserList)
      ReqOnlineUserListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqOnlineUserList.newBuilder() to construct.
    private ReqOnlineUserList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqOnlineUserList() {
      keyword_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReqOnlineUserList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqOnlineUserList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              keyword_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList.class, net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList.Builder.class);
    }

    public static final int KEYWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object keyword_;
    /**
     * <pre>
     * 搜索关键字
     * </pre>
     *
     * <code>string keyword = 2;</code>
     * @return The keyword.
     */
    @java.lang.Override
    public java.lang.String getKeyword() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyword_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 搜索关键字
     * </pre>
     *
     * <code>string keyword = 2;</code>
     * @return The bytes for keyword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeywordBytes() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(keyword_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, keyword_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(keyword_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, keyword_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList)) {
        return super.equals(obj);
      }
      net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList other = (net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList) obj;

      if (!getKeyword()
          .equals(other.getKeyword())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
      hash = (53 * hash) + getKeyword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求在线用户列表
     * </pre>
     *
     * Protobuf type {@code net.sopod.soim.data.msg.user.ReqOnlineUserList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.sopod.soim.data.msg.user.ReqOnlineUserList)
        net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList.class, net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList.Builder.class);
      }

      // Construct using net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        keyword_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_descriptor;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList getDefaultInstanceForType() {
        return net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList.getDefaultInstance();
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList build() {
        net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList buildPartial() {
        net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList result = new net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList(this);
        result.keyword_ = keyword_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList) {
          return mergeFrom((net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList other) {
        if (other == net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList.getDefaultInstance()) return this;
        if (!other.getKeyword().isEmpty()) {
          keyword_ = other.keyword_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object keyword_ = "";
      /**
       * <pre>
       * 搜索关键字
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @return The keyword.
       */
      public java.lang.String getKeyword() {
        java.lang.Object ref = keyword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 搜索关键字
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @return The bytes for keyword.
       */
      public com.google.protobuf.ByteString
          getKeywordBytes() {
        java.lang.Object ref = keyword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 搜索关键字
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @param value The keyword to set.
       * @return This builder for chaining.
       */
      public Builder setKeyword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyword_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索关键字
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyword() {
        
        keyword_ = getDefaultInstance().getKeyword();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索关键字
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @param value The bytes for keyword to set.
       * @return This builder for chaining.
       */
      public Builder setKeywordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keyword_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.sopod.soim.data.msg.user.ReqOnlineUserList)
    }

    // @@protoc_insertion_point(class_scope:net.sopod.soim.data.msg.user.ReqOnlineUserList)
    private static final net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList();
    }

    public static net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqOnlineUserList>
        PARSER = new com.google.protobuf.AbstractParser<ReqOnlineUserList>() {
      @java.lang.Override
      public ReqOnlineUserList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqOnlineUserList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqOnlineUserList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqOnlineUserList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.sopod.soim.data.msg.user.UserGroup.ReqOnlineUserList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResOnlineUserListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.sopod.soim.data.msg.user.ResOnlineUserList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    java.util.List<net.sopod.soim.data.msg.user.UserMsg.UserInfo> 
        getUsersList();
    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    net.sopod.soim.data.msg.user.UserMsg.UserInfo getUsers(int index);
    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    int getUsersCount();
    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    java.util.List<? extends net.sopod.soim.data.msg.user.UserMsg.UserInfoOrBuilder> 
        getUsersOrBuilderList();
    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    net.sopod.soim.data.msg.user.UserMsg.UserInfoOrBuilder getUsersOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 响应在线用户列表
   * </pre>
   *
   * Protobuf type {@code net.sopod.soim.data.msg.user.ResOnlineUserList}
   */
  public static final class ResOnlineUserList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.sopod.soim.data.msg.user.ResOnlineUserList)
      ResOnlineUserListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResOnlineUserList.newBuilder() to construct.
    private ResOnlineUserList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResOnlineUserList() {
      users_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResOnlineUserList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResOnlineUserList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                users_ = new java.util.ArrayList<net.sopod.soim.data.msg.user.UserMsg.UserInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              users_.add(
                  input.readMessage(net.sopod.soim.data.msg.user.UserMsg.UserInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          users_ = java.util.Collections.unmodifiableList(users_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList.class, net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList.Builder.class);
    }

    public static final int USERS_FIELD_NUMBER = 2;
    private java.util.List<net.sopod.soim.data.msg.user.UserMsg.UserInfo> users_;
    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    @java.lang.Override
    public java.util.List<net.sopod.soim.data.msg.user.UserMsg.UserInfo> getUsersList() {
      return users_;
    }
    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends net.sopod.soim.data.msg.user.UserMsg.UserInfoOrBuilder> 
        getUsersOrBuilderList() {
      return users_;
    }
    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    @java.lang.Override
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    @java.lang.Override
    public net.sopod.soim.data.msg.user.UserMsg.UserInfo getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <pre>
     * 查询用户列表
     * </pre>
     *
     * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
     */
    @java.lang.Override
    public net.sopod.soim.data.msg.user.UserMsg.UserInfoOrBuilder getUsersOrBuilder(
        int index) {
      return users_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < users_.size(); i++) {
        output.writeMessage(2, users_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < users_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, users_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList)) {
        return super.equals(obj);
      }
      net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList other = (net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList) obj;

      if (!getUsersList()
          .equals(other.getUsersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUsersCount() > 0) {
        hash = (37 * hash) + USERS_FIELD_NUMBER;
        hash = (53 * hash) + getUsersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 响应在线用户列表
     * </pre>
     *
     * Protobuf type {@code net.sopod.soim.data.msg.user.ResOnlineUserList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.sopod.soim.data.msg.user.ResOnlineUserList)
        net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList.class, net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList.Builder.class);
      }

      // Construct using net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUsersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          usersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sopod.soim.data.msg.user.UserGroup.internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_descriptor;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList getDefaultInstanceForType() {
        return net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList.getDefaultInstance();
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList build() {
        net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList buildPartial() {
        net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList result = new net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList(this);
        int from_bitField0_ = bitField0_;
        if (usersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            users_ = java.util.Collections.unmodifiableList(users_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.users_ = users_;
        } else {
          result.users_ = usersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList) {
          return mergeFrom((net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList other) {
        if (other == net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList.getDefaultInstance()) return this;
        if (usersBuilder_ == null) {
          if (!other.users_.isEmpty()) {
            if (users_.isEmpty()) {
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUsersIsMutable();
              users_.addAll(other.users_);
            }
            onChanged();
          }
        } else {
          if (!other.users_.isEmpty()) {
            if (usersBuilder_.isEmpty()) {
              usersBuilder_.dispose();
              usersBuilder_ = null;
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
              usersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUsersFieldBuilder() : null;
            } else {
              usersBuilder_.addAllMessages(other.users_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<net.sopod.soim.data.msg.user.UserMsg.UserInfo> users_ =
        java.util.Collections.emptyList();
      private void ensureUsersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          users_ = new java.util.ArrayList<net.sopod.soim.data.msg.user.UserMsg.UserInfo>(users_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.sopod.soim.data.msg.user.UserMsg.UserInfo, net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder, net.sopod.soim.data.msg.user.UserMsg.UserInfoOrBuilder> usersBuilder_;

      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public java.util.List<net.sopod.soim.data.msg.user.UserMsg.UserInfo> getUsersList() {
        if (usersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(users_);
        } else {
          return usersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public int getUsersCount() {
        if (usersBuilder_ == null) {
          return users_.size();
        } else {
          return usersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public net.sopod.soim.data.msg.user.UserMsg.UserInfo getUsers(int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);
        } else {
          return usersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public Builder setUsers(
          int index, net.sopod.soim.data.msg.user.UserMsg.UserInfo value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.set(index, value);
          onChanged();
        } else {
          usersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public Builder setUsers(
          int index, net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.set(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public Builder addUsers(net.sopod.soim.data.msg.user.UserMsg.UserInfo value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(value);
          onChanged();
        } else {
          usersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public Builder addUsers(
          int index, net.sopod.soim.data.msg.user.UserMsg.UserInfo value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(index, value);
          onChanged();
        } else {
          usersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public Builder addUsers(
          net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public Builder addUsers(
          int index, net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public Builder addAllUsers(
          java.lang.Iterable<? extends net.sopod.soim.data.msg.user.UserMsg.UserInfo> values) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, users_);
          onChanged();
        } else {
          usersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public Builder clearUsers() {
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          usersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public Builder removeUsers(int index) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.remove(index);
          onChanged();
        } else {
          usersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder getUsersBuilder(
          int index) {
        return getUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public net.sopod.soim.data.msg.user.UserMsg.UserInfoOrBuilder getUsersOrBuilder(
          int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);  } else {
          return usersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public java.util.List<? extends net.sopod.soim.data.msg.user.UserMsg.UserInfoOrBuilder> 
           getUsersOrBuilderList() {
        if (usersBuilder_ != null) {
          return usersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(users_);
        }
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder addUsersBuilder() {
        return getUsersFieldBuilder().addBuilder(
            net.sopod.soim.data.msg.user.UserMsg.UserInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder addUsersBuilder(
          int index) {
        return getUsersFieldBuilder().addBuilder(
            index, net.sopod.soim.data.msg.user.UserMsg.UserInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 查询用户列表
       * </pre>
       *
       * <code>repeated .net.sopod.soim.data.msg.user.UserInfo users = 2;</code>
       */
      public java.util.List<net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder> 
           getUsersBuilderList() {
        return getUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.sopod.soim.data.msg.user.UserMsg.UserInfo, net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder, net.sopod.soim.data.msg.user.UserMsg.UserInfoOrBuilder> 
          getUsersFieldBuilder() {
        if (usersBuilder_ == null) {
          usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.sopod.soim.data.msg.user.UserMsg.UserInfo, net.sopod.soim.data.msg.user.UserMsg.UserInfo.Builder, net.sopod.soim.data.msg.user.UserMsg.UserInfoOrBuilder>(
                  users_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          users_ = null;
        }
        return usersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.sopod.soim.data.msg.user.ResOnlineUserList)
    }

    // @@protoc_insertion_point(class_scope:net.sopod.soim.data.msg.user.ResOnlineUserList)
    private static final net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList();
    }

    public static net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResOnlineUserList>
        PARSER = new com.google.protobuf.AbstractParser<ResOnlineUserList>() {
      @java.lang.Override
      public ResOnlineUserList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResOnlineUserList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResOnlineUserList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResOnlineUserList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.sopod.soim.data.msg.user.UserGroup.ResOnlineUserList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/user/UserGroup.proto\022\034net.sopod." +
      "soim.data.msg.user\032\030proto/user/UserMsg.p" +
      "roto\"$\n\021ReqOnlineUserList\022\017\n\007keyword\030\002 \001" +
      "(\t\"J\n\021ResOnlineUserList\0225\n\005users\030\002 \003(\0132&" +
      ".net.sopod.soim.data.msg.user.UserInfoB\r" +
      "B\tUserGroupP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.sopod.soim.data.msg.user.UserMsg.getDescriptor(),
        });
    internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_sopod_soim_data_msg_user_ReqOnlineUserList_descriptor,
        new java.lang.String[] { "Keyword", });
    internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_sopod_soim_data_msg_user_ResOnlineUserList_descriptor,
        new java.lang.String[] { "Users", });
    net.sopod.soim.data.msg.user.UserMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
