spring:
  application:
    name: im-logic-group

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    port: 3013
  consumer:
    check: false
  provider:
    retries: 0
    timeout: 2000
    filter: soimExceptionFilter,-exception